### ISSUE TITLE
Faction API

### ISSUE THREAD

**Issue by kangarko** [DRE2N/FactionsOne#1]
Hello,

I am sorry if I am blind but I was unable to find an api for following:
> faction name, faction role, claimed chunks amount, kdr and faction title

This have been requested by one of my plugin's user and I would like to create a variable for it.

**Comment by Feuerstern** [comment]
Faction name: Faction#getTag()

Faction role: FPlayer#getRel()

Claimed chunks amount: Faction#getLandRounded() / Board#getFactionCoordCount(Faction)

Player title: FPlayer#getTitle()

You can get a faction with Factions.i.getbyTag(String) and an FPlayer with FPlayers.i.get(Player).

You may also use the new API additions:

https://github.com/DRE2N/FactionsOne/blob/FactionsOne/src/main/java/io/github/dre2n/factionsone/api/Placeholders.java

These will be added in FactionsOne 1.3.

**Comment by kangarko** [comment]
Thank you!

What about the kdr? I am not familiar with the plugin so I am not quite sure what the user needs.

**Comment by Feuerstern** [comment]
Me neither. WTF is "kdr"?

**Comment by kangarko** [comment]
It was a _kill death ratio_. Not related to factions.

Thanks for your help.
