### ISSUE TITLE
zPermission and FactionsOne

### ISSUE THREAD

**Issue by nightdeploy** [DRE2N/FactionsOne#10]
So whenever i install Factions one in my plugins directory it loads up normally but breaks zPermissions and zChatfor some reason. Is this a known bug?

**Comment by Sataniel98** [comment]
What do you mean by "breaks"? For zChat, it's probably the chat formatting. How does your setup look like?

**Comment by nightdeploy** [comment]
Well at the moment i cant show you my configs but tomorrow i will be able to update you on the problem
