### ISSUE TITLE
Faction Relation Color

### ISSUE THREAD

**Issue by jtriskele** [DRE2N/FactionsOne#11]
Hello. I was wondering if there was any way that I could set this plugin up to show faction relations in server chat. Let me show you what I mean by this.
![fquestion](https://cloud.githubusercontent.com/assets/20294748/16576325/078ba512-4254-11e6-8a25-2507e83293a0.png)
If someone else is in my faction "Triskelion" I want their faction prefix to be shown in green like it is in the /f list. If a player is in an enemy faction like "Niger" I want their faction prefix to appear red just as it is in the /f list. Is there any way I can set this?
Also, I changed this in my Essentials config assuming that's what I was supposed to do. But as you can see, {faction_relcolor} isn't working.
![fquestion2](https://cloud.githubusercontent.com/assets/20294748/16576704/7f88b67a-4256-11e6-8cd6-68c344d3206b.png)

**Comment by Sataniel98** [comment]
Well, it's up to the chat plugins to support placeholders or not to do so. The best Factions chat plugin around is definitely FactionChat.
