### ISSUE TITLE
/f perm

### ISSUE THREAD

**Issue by jtriskele** [DRE2N/FactionsOne#12]
This isn't much of a problem it's just really annoying. When trying to set up perms for a faction, it automatically assumes that you're referring to "Wilderness". If you just do "/f perm set build ally no" you get this message
![fquestion3](https://cloud.githubusercontent.com/assets/20294748/16577865/398c7434-425d-11e6-89bc-b2a810d9b40f.png)
This is annoying because I have a rather long faction name and having to retype it every single time gets frustrating. Is there anything I can do to make it so I can just do "/f perm set build ally no" and have it set the perms for my own factions rather than telling me that I'm trying to change the perms for wilderness?

**Comment by Sataniel98** [comment]
Should easily be possible to change this.
