### ISSUE TITLE
Chest Access In Enemy Territory

### ISSUE THREAD

**Issue by butterontoast7** [DRE2N/FactionsOne#15]
I cant find the container permission in factions config, where is it so I can allow players to open chests in enemy territory?!

**Comment by Sataniel98** [comment]
It's not a permission but a flag. Try the flag overrides options or allow the players to use them themselves with /f flag.

**Comment by SheadyPro** [comment]
found the solution?

**Comment by Sataniel98** [comment]
Well, just what I wrote.

**Comment by SheadyPro** [comment]
That didn't fix the issue.
