### ISSUE TITLE
Factions color prefix

### ISSUE THREAD

**Issue by CyrexSwift** [DRE2N/FactionsOne#17]
Hey,
I installed FactionsOne onto my server weeks ago, I've found a weird bug that i haven't been able to fix.
Factions don't have any color in their prefixes, My friend has had the same problem on his server and we have no clue how to fix it.

Here is a screenshot I took: 
![2016-08-09_23 32 46](https://cloud.githubusercontent.com/assets/20926388/17514953/aa1ec402-5e89-11e6-9c17-22747b665183.png)

Thanks, Have a good one.

**Comment by Sataniel98** [comment]
Do you have colors enabled in the condig?

**Comment by CyrexSwift** [comment]
yes, I do.

**Comment by Sataniel98** [comment]
Do you use another plugin that overrides the chat formatting?

**Comment by CyrexSwift** [comment]
No, The only chat plugin i use is EssentialsChat.

**Comment by CyrexSwift** [comment]
Did you ever find a fix to this problem? I've still been trying to fix it.

**Comment by Sataniel98** [comment]
Well, if {faction_relcolor} doesn't work and colors are enabled in the config there's not really anything I could do. EssentialsChat is not my plugin...
