### ISSUE TITLE
Factions role showing for factionsless members. 

### ISSUE THREAD

**Issue by MTM123** [DRE2N/FactionsOne#18]
Version: FactionsOne v1.2.1

_1) I changed   "colorNeutral" from "WHITE" to "GRAY". Now it only shows that color even though I'm member of that faction so it should display color green(by default)._ FIXED(forgot to turn on chatParseTagColors)

2) Role prefix is showing ("+" by default) for factionless players by using tag: {faction_roleprefix} for formating

**Comment by Sataniel98** [comment]
Yes, because they are members of "Wilderness".

**Comment by MTM123** [comment]
Is there any way to fix it?

**Comment by Sataniel98** [comment]
Well, it's not wrong, so no. You can remove the + for all members, though: Just stop the server and modify the prefix in the conf.json (/f config won't work because MC doesn't allow empty arguments).

**Comment by MTM123** [comment]
Not exactly what I was looking for. Guess I'll try remove through AsyncPlayerchatevent. 
Thanks for your time!
