### ISSUE TITLE
FactionsOne causes errors with chat management plugins

### ISSUE THREAD

**Issue by LuluSupreme** [DRE2N/FactionsOne#2]
When I installed FactionsOne the chat management plugin I have quit working (chatex) I tried to use a few others but the same error pops up with every one. Here is the error that is sends when a player talks http://pastebin.com/aFdcuZjF

This is what the chat looks like while FactionsOne is installed
![stupid peice of shit](https://cloud.githubusercontent.com/assets/10571625/13445162/7cd655c6-dfbf-11e5-802b-c24bb1828274.png)

This is what its supposed to look like to look like
![what is looks like](https://cloud.githubusercontent.com/assets/10571625/13445163/7e004ba0-dfbf-11e5-80c2-549c6c25d4e0.png)

**Comment by Feuerstern** [comment]
Did you modify the chat settings in the config?

**Comment by LuluSupreme** [comment]
In the FactionsOne config? Or the ChatEx config?

**Comment by Feuerstern** [comment]
FactionsOne :)

**Comment by LuluSupreme** [comment]
I dont see the setting in the config, would you mind pointing it out? If so that would be great :)

**Comment by Feuerstern** [comment]
```
  "chatSetFormat": false,
  "chatSetFormatTo": "<{faction_relcolor}Ã‚Â§l{faction_roleprefix}Ã‚Â§r{faction_relcolor}{faction_tag_pr}Â§f%s> %s",
  "chatParseTags": true,
  "chatParseTagsColored": false,
  "chatSingleFormats": {
    "pb": " %s ",
    "pl": " %s",
    "pr": "%s "
  },
  "chatTagFormat": "%sÂ§f",
```

**Comment by LuluSupreme** [comment]
Awesome! When I get home I'll see if that works (fingers crossed)

**Comment by LuluSupreme** [comment]
Sadly its still sending the error :\

**Comment by Feuerstern** [comment]
So, what do you try?

**Comment by LuluSupreme** [comment]
Mine looks like yours.

**Comment by Feuerstern** [comment]
The problem is that ChatEx has some kind of Factions support and that it recognizes FactionsOne as Factions 2.x. It tries to interact with FactionsOne the way it interacts with Factions 2.x. This doesn't work, because FactionsOne and Factions 2.x have technically nothing at all to do with each other.

**Comment by Feuerstern** [comment]
Fixed it in ChatEx :)

**Comment by LuluSupreme** [comment]
Thanks, how can I download that?

**Comment by Feuerstern** [comment]
If you don't know how to use Maven, I could compile it for you as soon as I'm at home.

**Comment by LuluSupreme** [comment]
That would be the best! Thanks :)

**Comment by Feuerstern** [comment]
No problem :)
http://feuerstern.bplaced.net/files/ChatEx.jar

**Comment by LuluSupreme** [comment]
Thanks man! That worked :) You have made this a LOT easier
