### ISSUE TITLE
Can you make a custom ore respawner plugin that can be used in warzones?

### ISSUE THREAD

**Issue by ZombiePwner1** [DRE2N/FactionsOne#22]
So i'm looking at getting my buddie to download this factions plugin. for his server which i'm an admin and there is one thing i wanted to ask you. Are you able to make a custom ore respawn plugin that you can set on ores to make them respawn when there is loads of players online and they take longer to respawn when less players are online? Of course this would be a  server admin only command. And the way this works is it's put in a warzone but the ore that has been set to respawn can be destroyed in the warzone. I got this from another server with a custom clans plugin pvp.battleau.net There is also a plugin called replenish but it's quite outdated and abit buggy so this is why i'm suggesting if you can make a custom ore respawn plugin.

**Comment by Sataniel98** [comment]
I am, but I don't have time and will to work on plugins that are specialized for the needs of few servers if I don't even have any use for them. You should hire a developer or do it yourself.

**Comment by ZombiePwner1** [comment]
Yes we have been trying to get developers but we haven't got any luck and i don't know a good place to find actual developers.

**Comment by ZombiePwner1** [comment]
Do you perhaps know any good places to find developers?

**Comment by Sataniel98** [comment]
You can hire developers at SpigotMC.org. Many devs provide portfolios there.

**Comment by ZombiePwner1** [comment]
alright.
