### ISSUE TITLE
Uhm not sure about this issue lol

### ISSUE THREAD

**Issue by dudemanmax49** [DRE2N/FactionsOne#23]
`01.01 05:29:23 [Server] ERROR Error occurred while enabling Factions v1.8.2 (Is it up to date?)
01.01 05:29:23 [Server] INFO java.lang.NoClassDefFoundError: com/earth2me/essentials/IEssentials
01.01 05:29:23 [Server] INFO at com.massivecraft.factions.integration.Essentials.setup(Essentials.java:21) ~[?:?]
01.01 05:29:23 [Server] INFO at com.massivecraft.factions.P.onEnable(P.java:111) ~[?:?]
01.01 05:29:23 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
01.01 05:29:23 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
01.01 05:29:23 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
01.01 05:29:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
01.01 05:29:23 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1278) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1138) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
01.01 05:29:23 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
01.01 05:29:23 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.IEssentials
01.01 05:29:23 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
01.01 05:29:23 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[custom.jar:git-Bukkit-0a81101]
01.01 05:29:23 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
01.01 05:29:23 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]`

**Comment by Sataniel98** [comment]
It's either an incompatible plugin called "Essentials" which is not the popular one or PlugMan's problem.

**Comment by tizakk** [comment]
I'm not sure if you are using [EssentialX](https://ci.drtshock.net/job/EssentialsX/), but you could try updating to that as it's maintained.
