### ISSUE TITLE
How do i get factionsone 1.8.4?

### ISSUE THREAD

**Issue by Spiizy1255** [DRE2N/FactionsOne#25]
How do i get that? I tried 1.8.3 works for a day and then turns itself off afterwards? So im looking for a 1.8.4 version of factionsone
can someone please link me to the download?
or explain why it doesnt work

**Comment by Sataniel98** [comment]
If you want help, offer information. I can't help you without information. The 1.8.3-1.8.8 build works with 1.8.4 unless you do something wrong.

**Comment by Spiizy1255** [comment]
Can you link me to it please? Because it says im missing a GSON Lib

**Comment by Sataniel98** [comment]
If it says you're missing GSON, you must be using a build where GSON was at the old org.bukkit.craftbukkit.libs position instead of its natural one. Which is not the case for 1.8.4 but for 1.8 and lower
