### ISSUE TITLE
CratesPlus+Factionsone help!

### ISSUE THREAD

**Issue by Shootingisgood9** [DRE2N/FactionsOne#29]
I have CratesPlus and my players can't use crates because I put it in safezone(I have worldguard but doesn
't change)and I have to claim or they will and they will mess up spawn.Is there a way to make a certain area unclaimble?

**Comment by Sataniel98** [comment]
You can enable WorldGuard checks with "/f config worldGuardChecking true" if I remember it correctly.

**Comment by Shootingisgood9** [comment]
No I mean like can you make an area unclaimble?

**Comment by Sataniel98** [comment]
This should make all WorldGuard areas unclaimable.

**Comment by Shootingisgood9** [comment]
ok thx
