### ISSUE TITLE
Internal Error?

### ISSUE THREAD

**Issue by Kieran7213** [DRE2N/FactionsOne#3]
"An internal error occured while attempting to perform this command"

What does this mean and how do I fix it?

Thanks!

**Comment by Kieran7213** [comment]
Never mind!

I downloaded the 1.9.x version by accident and tried to run it on a 1.8.x server :D 

Thanks again!

**Comment by Feuerstern** [comment]
No problem! By the way: If you want to use one of the snapshots for 1.9 with 1.8.x, you can patch them with 7zip, WinRAR or a similar program. Just open the 1.2.1 jar, navigate to com/massivecraft/factions and copy the Conf.class file to the same position in 1.3-SNAPSHOT ;)
