### ISSUE TITLE
Land Claiming Next To Other Factions

### ISSUE THREAD

**Issue by xXBuilderBXx** [DRE2N/FactionsOne#4]
Hey can you add a feature to FactionsOne so that claims cannot be next to each other for example factiona has a claim and factionb cannot claim next to factiona's land unless it is (X) number of blocks/chunks away or if the power of the faction is low enough factionb can claim factiona's land.

I know that this is a feature in the original factions plugin but it would be really good feature to have.
Currently i have my server setup with minecraft 1.8 factionsone 1.2.1 and lwc integration. If not i can deal with it and let people claim anywhere.

**Comment by Feuerstern** [comment]
Hi, I usually don't add any new features and use addons instead to keep FactionsOne as close as possible to the original Factions 1.8.2. I'll create one for minor additional features like this one probably in a few months.

**Comment by xXBuilderBXx** [comment]
Ok cool also with the new updates of 1.2.2 and up it wont work with 1.8 or is it not backwards compatible.

**Comment by Feuerstern** [comment]
Correct.
