### ISSUE TITLE
Add a getClaims method (Java API) 

### ISSUE THREAD

**Issue by MarkehMe** [DRE2N/FactionsOne#5]
Not sure if this is already implement. Is there a way to get all claims for a Faction?

Be nice to have a ```Faction#getClaims()``` method, if you accept pull requests I'll add it.

**Comment by Sataniel98** [comment]
Sounds like a good idea. I'll add one!

**Comment by MarkehMe** [comment]
Thanks! Trying to implement FactionsOne into [FactionsFramework](https://github.com/MarkehMe/FactionsFramework) 😄

**Comment by Sataniel98** [comment]
Yes, I noticed that also :) Didn't you already have this or a similar project a few months ago which hasn't been continued? Seems like a great project.

**Comment by Sataniel98** [comment]
I've added a method to the Board class. Should work fine as it actually does exactly the same as the unclaimAll method (except that it returns the FLocations in a Set instead of removing them). I also added a wrapper to the Faction class called getClaims().

**Comment by MarkehMe** [comment]
I started FactionsLib not too long ago but dumped it due to lack of time/life stuff. Turned that all around with FactionsFramework though 😄  I'm really excited to add the FactionsOne compatibility layer. 

Just referencing this ticket to keep everything nicely organised: https://github.com/MarkehMe/FactionsFramework/issues/3

**Comment by Sataniel98** [comment]
Feel free to ask for further additions :) By the way, a build with the latest changes is now available at the repo.
