### ISSUE TITLE
Allow LandUnclaimAllEvent to be cancelled 

### ISSUE THREAD

**Issue by MarkehMe** [DRE2N/FactionsOne#6]
The event ```LandUnclaimAllEvent``` cannot be cancelled. 

Not sure why this wasn't allowed by default but @eueln implemented this into FactionsUUID (https://github.com/drtshock/Factions/commit/3c2e51e8eda8f946ab652321f67acd5466484fb6)

Could this be added? I can open a pull request if needed. 😃

**Comment by Sataniel98** [comment]
Done ;)

**Comment by MarkehMe** [comment]
Great stuff. Thanks 👍
